import { expect, test } from '@playwright/test'

test('opens the project Python editor with syntax highlighting', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Project actions' }).click()
  await page.getByRole('menuitem', { name: /Project Python/ }).click()

  const dialog = page.getByRole('dialog', { name: 'Project Python' })
  await expect(dialog).toBeVisible()
  await expect(dialog.locator('.cm-editor')).toContainText('def process(context):')
  const symbolSelect = dialog.getByRole('combobox', { name: 'Python symbols' })
  await expect(symbolSelect).toBeVisible()
  const [symbolBox, tabBarBox] = await Promise.all([
    symbolSelect.boundingBox(),
    dialog.locator('.ant-tabs-nav').boundingBox(),
  ])
  expect(symbolBox).not.toBeNull()
  expect(tabBarBox).not.toBeNull()
  expect(symbolBox!.y).toBeGreaterThanOrEqual(tabBarBox!.y)
  expect(symbolBox!.y + symbolBox!.height).toBeLessThanOrEqual(tabBarBox!.y + tabBarBox!.height + 1)
  await symbolSelect.click()
  const processSymbol = page.locator('.python-project-symbol-title').filter({ hasText: 'process' })
  await expect(processSymbol).toBeVisible()
  await expect(page.locator('.python-project-symbol-icon.is-function')).toBeVisible()
  await processSymbol.click()
  const highlightedDef = dialog.locator('.cm-line span').filter({ hasText: /^def$/ }).first()
  await expect(highlightedDef).toBeVisible()
  await expect(highlightedDef).not.toHaveAttribute('class', '')
  await expect(highlightedDef).toHaveCSS('color', 'rgb(136, 57, 239)')
  await expect(dialog.locator('.cm-editor')).toHaveCSS('background-color', 'rgb(239, 241, 245)')
  await expect(dialog.getByText('No current parse result')).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Run' })).toBeDisabled()

  const editor = dialog.locator('.cm-content')
  await editor.click()
  await page.keyboard.press(process.platform === 'darwin' ? 'Meta+End' : 'Control+End')
  await page.keyboard.down('x')
  for (let index = 1; index < 12; index += 1) await page.keyboard.down('x')
  await page.keyboard.up('x')
  await expect(editor).toContainText('xxxxxxxxxxxx')

  await page.keyboard.press(process.platform === 'darwin' ? 'Meta+A' : 'Control+A')
  await page.keyboard.insertText('def helper():\n    return 1\n\ndef process(context):\n    return helper()')
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('F12')
  await expect(dialog.locator('.cm-activeLine')).toContainText('def helper():')
})

test('shows hierarchical symbols and modifier-hover definition links', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Project actions' }).click()
  await page.getByRole('menuitem', { name: /Project Python/ }).click()

  const dialog = page.getByRole('dialog', { name: 'Project Python' })
  const editor = dialog.locator('.cm-content')
  await editor.click()
  await page.keyboard.press(process.platform === 'darwin' ? 'Meta+A' : 'Control+A')
  await page.keyboard.insertText('class Builder:\n    def render(self):\n        return helper()\n\ndef helper():\n    return 1\n\ndef process(context):\n    return helper()')

  await dialog.getByRole('combobox', { name: 'Python symbols' }).click()
  const symbolTree = page.locator('.ant-select-tree')
  const builderLabel = symbolTree.getByText('Builder', { exact: true })
  const renderLabel = symbolTree.getByText('render', { exact: true })
  const builderTitle = builderLabel.locator('..')
  const renderTitle = renderLabel.locator('..')
  await expect(builderTitle.locator('.python-project-symbol-icon.is-class')).toBeVisible()
  await expect(renderTitle.locator('.python-project-symbol-icon.is-method')).toBeVisible()
  await expect(builderTitle).toHaveCSS('padding-left', '0px')
  await expect(renderTitle).toHaveCSS('padding-left', '12px')
  await builderTitle.click()

  const helperLine = dialog.locator('.cm-line').filter({ hasText: 'return helper()' }).last()
  const helperReference = helperLine.locator('span').filter({ hasText: /^helper$/ }).last()
  const modifier = process.platform === 'darwin' ? 'Meta' : 'Control'
  const helperBox = await helperReference.boundingBox()
  expect(helperBox).not.toBeNull()
  await page.keyboard.down(modifier)
  await page.mouse.move(helperBox!.x + helperBox!.width / 2, helperBox!.y + helperBox!.height / 2)
  const definitionLink = helperLine.locator('.cm-python-definition-link')
  await expect(definitionLink).toHaveCSS('text-decoration-line', 'underline')
  await page.keyboard.up(modifier)
  await expect(definitionLink).toHaveCount(0)
})

test('distinguishes constructors and navigates through an inferred instance type', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Project actions' }).click()
  await page.getByRole('menuitem', { name: /Project Python/ }).click()

  const dialog = page.getByRole('dialog', { name: 'Project Python' })
  const editor = dialog.locator('.cm-content')
  await editor.click()
  await page.keyboard.press(process.platform === 'darwin' ? 'Meta+A' : 'Control+A')
  await page.keyboard.insertText('class Builder:\n    def render(self, value: int):\n        return value\n\ndef process(context):\n    builder = Builder()\n    return builder.render(1)')

  const constructor = dialog.locator('.cm-python-constructor').filter({ hasText: 'Builder' })
  const method = dialog.locator('.cm-python-method').filter({ hasText: 'render' }).last()
  await expect(constructor).toHaveCSS('color', 'rgb(23, 146, 153)')
  await expect(method).toHaveCSS('color', 'rgb(114, 135, 253)')

  await method.click()
  await page.keyboard.press('F12')
  await expect(dialog.locator('.cm-activeLine')).toContainText('def render(self, value: int):')

  await editor.fill('class Base:\n    def render(self, value: int):\n        return value\n\nclass Builder(Base):\n    pass\n\ndef process(context):\n    builder = Builder()\n    return builder')
  await editor.press('.')
  const completion = dialog.locator('.cm-tooltip-autocomplete').getByText(/render.*inherited from Base/)
  await expect(completion).toBeVisible()
})
