import { expect, test } from '@playwright/test'

test('opens the project Python editor with syntax highlighting', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Project actions' }).click()
  await page.getByRole('menuitem', { name: /Project Python/ }).click()

  const dialog = page.getByRole('dialog', { name: 'Project Python' })
  await expect(dialog).toBeVisible()
  await expect(dialog.locator('.cm-editor')).toContainText('def process(context):')
  await expect(dialog.getByRole('combobox', { name: 'Python symbols' })).toBeVisible()
  await dialog.getByRole('combobox', { name: 'Python symbols' }).click()
  await expect(page.getByText('process · line 1')).toBeVisible()
  await page.keyboard.press('Escape')
  const highlightedDef = dialog.locator('.cm-line span').filter({ hasText: /^def$/ }).first()
  await expect(highlightedDef).toBeVisible()
  await expect(highlightedDef).not.toHaveAttribute('class', '')
  await expect(highlightedDef).toHaveCSS('color', 'rgb(155, 47, 105)')
  await expect(dialog.locator('.cm-editor')).toHaveCSS('background-color', 'rgb(251, 252, 254)')
  await expect(dialog.getByText('No current parse result')).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Run' })).toBeDisabled()

  const editor = dialog.locator('.cm-content')
  await editor.click()
  await page.keyboard.press(process.platform === 'darwin' ? 'Meta+End' : 'Control+End')
  await page.keyboard.down('x')
  for (let index = 1; index < 12; index += 1) await page.keyboard.down('x')
  await page.keyboard.up('x')
  await expect(editor).toContainText('xxxxxxxxxxxx')

  await page.keyboard.press(process.platform === 'darwin' ? 'Meta+A' : 'Control+A')
  await page.keyboard.insertText('def helper():\n    return 1\n\ndef process(context):\n    return helper()')
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('F12')
  await expect(dialog.locator('.cm-activeLine')).toContainText('def helper():')
})
